apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: rollouts-demo-
labels:
  - pairs:
      app: rollouts-demo
    includeSelectors: true
  - pairs:
      env: sit
    includeTemplates: true

resources:
  - ../../base

replicas:
  - name: deploy
    count: 2

patches:
  - target:
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: rollouts-demo-ing-rollouts-demo-sit.apps.q4n4p.dynamic.redhatworkshops.io
