apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Service
    patch: | # yaml
      kind: __kind__
      metadata:
        name: __name__
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
