apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: rollouts-demo-
labels:
  - pairs:
      env: prod

resources:
  - ../../base

components:
  - ../../components/blue-labels
  - ../../components/tmp-service
  - ../../components/rollout

replicas:
  - name: deploy
    count: 0
  - name: rollout
    count: 4

patches:
  - target:
      name: deploy
    patch: | # yaml
      - op: add
        path: /spec/template/metadata/labels/env
        value: prod
  - target:
      name: ing
    patch: | # yaml
      - op: replace
        path: /spec/rules/0/host
        value: rollouts-demo-ing-rollouts-demo.apps.q4n4p.dynamic.redhatworkshops.io
