apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: rollouts-demo-
labels:
  - pairs:
      app: rollouts-demo
    includeSelectors: true
  - pairs:
      env: prod
    includeTemplates: true
  # - pairs:
  #     blue-green.rollout/zone: blue

resources:
  - ../../base

components:
  - ../../components/green-svc

replicas:
  - name: deploy
  #   count: 0
  # - name: rollout
    count: 4

patches:
  # - target:
  #     kind: Rollout
  #   patch: |
  #     - op: remove
  #       path: /spec/selector
  #     - op: remove
  #       path: /spec/template
