apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# labels:
#   - pairs:
#       blue-green.rollout/zone: blue
#     includeTemplates: true # REVIEW: conflict with Argo Rollouts?

patches:
  - target: {}
    patch: | # yaml
      - op: add
        path: /metadata/labels/blue-green.rollout~1zone
        value: blue
