apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# labels:
#   - pairs:
#       blue-green.rollout/zone: blue
#     includeTemplates: true # REVIEW: conflict with Argo Rollouts?

patches:
  - target:
      # name: \*-green
      labelSelector: blue-green.rollout/zone!=green
    patch: |
      kind: __kind__
      metadata:
        name: __name__
        labels:
          blue-green.rollout/zone: blue
