apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: app
          image: placeholder
          ports:
            - containerPort: 8080
          #-# envFrom:
          #-#   - configMapRef:
          #-#       name: cm
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  replicas: 0
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy
  ## paused: false
  strategy:
    blueGreen:
      activeService: svc
      previewService: svc-green
      previewReplicaCount: 1
      autoPromotionEnabled: false
