apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This label config allows the base to be deployed standalone
labels:
  - pairs:
      app: __app__
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: __image__
    newName: argoproj/rollouts-demo
    newTag: red
