apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Deployment
replicas:
  - name: deploy
    count: 4
images:
  - name: <image>
    newName: argoproj/rollouts-demo
    newTag: purple
