apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: rollouts-demo-
labels:
  - pairs:
      app: rollouts-demo
    includeSelectors: true

resources:
  - route
  - service
  - deployment
  - rollout
