apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: rollouts-demo-
nameSuffix: -green
# REVIEW
labels:
  - pairs:
      blue-green.rollout/zone: green
    includeSelectors: true
  - pairs:
      env: prod
    includeTemplates: true

resources:
  - ../../base

# components:
#   - ../../components/green-ingress

replicas:
  - name: deploy
    count: 1

patches:
  - target:
      name: svc
    patch: | # yaml
      kind: __kind__
      metadata:
        name: __name__
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
  - target:
      name: ing
    patch: | # yaml
      kind: __kind__
      metadata:
        name: __name__
        annotations:
          nginx.ingress.kubernetes.io/canary: "true"
          nginx.ingress.kubernetes.io/canary-by-header: X-User-Type
          nginx.ingress.kubernetes.io/canary-by-header-value: Pilot
      spec:
        rules:
          - host: rollouts-demo-ing-rollouts-demo.apps.q4n4p.dynamic.redhatworkshops.io
