apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## configurations:
##   - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml
## crds:
##   - crds/kustomize-openshift/crds/openshift-route.json

namePrefix: rollouts-demo-
nameSuffix: -green
labels:
  - pairs:
      blue-green.rollout/zone: green
  - pairs:
      env: prod
    includeTemplates: true # REVIEW

resources:
  - ../../base

components:
  - ../../components/green-ingress

patches:
  - target:
      name: ing
    patch: | # yaml
      - op: replace
        path: /spec/rules/0/host
        value: rollouts-demo-ing-rollouts-demo.apps.q4n4p.dynamic.redhatworkshops.io
