apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    blue-green.rollout/zone: blue
spec:
  template:
    spec:
      containers:
        - name: app
          image: <image>
          ports:
            - containerPort: 8080
