apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

replicas:
  - name: deploy
    count: 4

images:
  - name: <placeholder>
    newName: argoproj/rollouts-demo
    newTag: red
